### PR TITLE
Improve UI

### PR DESCRIPTION
**Pull request by rafi0101**
see issue #34 

I hope this change is working for you

### CODE REVIEW

**Comment by hiteshvijayhv** [comment]
Tests not passing man. Can you send screenshot?

**Comment by rafi0101** [comment]
1. Please merge this #35 into your repo, unless it would not work. You deleted something that was still needed (see #35 for more information)

2. Screeenshots:
Main:
main

Add:
add

Edit:
edit

**Comment by hiteshvijayhv** [comment]
I reverted that change.

**Comment by hiteshvijayhv** [comment]
Great👌, It looks nice. I'll read all the code carefully, before merging

**Review by hiteshvijayhv — COMMENTED** [review]
@rafi0101 Can you split up the code, its too big and wide for a single commit. I advice you to open up a new PR and close this yourself and make a new commit for every change

**Comment by rafi0101** [comment]
Ok, but are the changes valid? 
Because when i make a new PR, and you will not add it, it is useless.

**Comment by hiteshvijayhv** [comment]
Those changes are too big for 1 single commit. Split up this time :) and yeah those were valid

**Comment by rafi0101** [comment]
see new PR #38

**Pull request closed without merging**
